# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helix/v1/orchestrator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'helix/v1/orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from helix.v1 import types_pb2 as helix_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhelix/v1/orchestrator.proto\x12\x08helix.v1\x1a\x14helix/v1/types.proto\"T\n\x15RegisterWorkerRequest\x12\x0c\n\x04pool\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x17\n\x0fmax_concurrency\x18\x03 \x01(\x05\"B\n\x16RegisterWorkerResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rlease_seconds\x18\x02 \x01(\x05\"J\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\tin_flight\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x05\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x64rain\x18\x01 \x01(\x08\";\n\x13\x43ompleteTaskRequest\x12$\n\x06result\x18\x01 \x01(\x0b\x32\x14.helix.v1.TaskResult\"+\n\x14\x43ompleteTaskResponse\x12\x13\n\x0b\x64isposition\x18\x01 \x01(\t\"K\n\x11\x43heckpointRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61ttempt_number\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x0c\"\x14\n\x12\x43heckpointResponse2\xc5\x02\n\x0cOrchestrator\x12S\n\x0eRegisterWorker\x12\x1f.helix.v1.RegisterWorkerRequest\x1a .helix.v1.RegisterWorkerResponse\x12H\n\tHeartbeat\x12\x1a.helix.v1.HeartbeatRequest\x1a\x1b.helix.v1.HeartbeatResponse(\x01\x30\x01\x12M\n\x0c\x43ompleteTask\x12\x1d.helix.v1.CompleteTaskRequest\x1a\x1e.helix.v1.CompleteTaskResponse\x12G\n\nCheckpoint\x12\x1b.helix.v1.CheckpointRequest\x1a\x1c.helix.v1.CheckpointResponseB6Z4github.com/tomiwaaluko/helix/gen/go/helix/v1;helixv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helix.v1.orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/tomiwaaluko/helix/gen/go/helix/v1;helixv1'
  _globals['_REGISTERWORKERREQUEST']._serialized_start=63
  _globals['_REGISTERWORKERREQUEST']._serialized_end=147
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=149
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=215
  _globals['_HEARTBEATREQUEST']._serialized_start=217
  _globals['_HEARTBEATREQUEST']._serialized_end=291
  _globals['_HEARTBEATRESPONSE']._serialized_start=293
  _globals['_HEARTBEATRESPONSE']._serialized_end=327
  _globals['_COMPLETETASKREQUEST']._serialized_start=329
  _globals['_COMPLETETASKREQUEST']._serialized_end=388
  _globals['_COMPLETETASKRESPONSE']._serialized_start=390
  _globals['_COMPLETETASKRESPONSE']._serialized_end=433
  _globals['_CHECKPOINTREQUEST']._serialized_start=435
  _globals['_CHECKPOINTREQUEST']._serialized_end=510
  _globals['_CHECKPOINTRESPONSE']._serialized_start=512
  _globals['_CHECKPOINTRESPONSE']._serialized_end=532
  _globals['_ORCHESTRATOR']._serialized_start=535
  _globals['_ORCHESTRATOR']._serialized_end=860
# @@protoc_insertion_point(module_scope)
