# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from helix.v1 import orchestrator_pb2 as helix_dot_v1_dot_orchestrator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in helix/v1/orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/helix.v1.Orchestrator/RegisterWorker',
                request_serializer=helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_stream(
                '/helix.v1.Orchestrator/Heartbeat',
                request_serializer=helix_dot_v1_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=helix_dot_v1_dot_orchestrator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/helix.v1.Orchestrator/CompleteTask',
                request_serializer=helix_dot_v1_dot_orchestrator__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=helix_dot_v1_dot_orchestrator__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.unary_unary(
                '/helix.v1.Orchestrator/Checkpoint',
                request_serializer=helix_dot_v1_dot_orchestrator__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=helix_dot_v1_dot_orchestrator__pb2.CheckpointResponse.FromString,
                _registered_method=True)


class OrchestratorServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=helix_dot_v1_dot_orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=helix_dot_v1_dot_orchestrator__pb2.HeartbeatResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=helix_dot_v1_dot_orchestrator__pb2.CompleteTaskRequest.FromString,
                    response_serializer=helix_dot_v1_dot_orchestrator__pb2.CompleteTaskResponse.SerializeToString,
            ),
            'Checkpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=helix_dot_v1_dot_orchestrator__pb2.CheckpointRequest.FromString,
                    response_serializer=helix_dot_v1_dot_orchestrator__pb2.CheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helix.v1.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helix.v1.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helix.v1.Orchestrator/RegisterWorker',
            helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerRequest.SerializeToString,
            helix_dot_v1_dot_orchestrator__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/helix.v1.Orchestrator/Heartbeat',
            helix_dot_v1_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
            helix_dot_v1_dot_orchestrator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helix.v1.Orchestrator/CompleteTask',
            helix_dot_v1_dot_orchestrator__pb2.CompleteTaskRequest.SerializeToString,
            helix_dot_v1_dot_orchestrator__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helix.v1.Orchestrator/Checkpoint',
            helix_dot_v1_dot_orchestrator__pb2.CheckpointRequest.SerializeToString,
            helix_dot_v1_dot_orchestrator__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
