# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helix/v1/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'helix/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14helix/v1/types.proto\x12\x08helix.v1\"\xed\x01\n\x0cTaskEnvelope\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x15\n\rworkflow_name\x18\x03 \x01(\t\x12\x18\n\x10workflow_version\x18\x04 \x01(\x05\x12\x0f\n\x07node_id\x18\x05 \x01(\t\x12\x12\n\ninput_json\x18\x06 \x01(\x0c\x12\x16\n\x0e\x61ttempt_number\x18\x07 \x01(\x05\x12\x10\n\x08trace_id\x18\x08 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\t \x01(\t\x12\x19\n\x0creplay_token\x18\n \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_replay_token\"\xb1\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61ttempt_number\x18\x02 \x01(\x05\x12\x11\n\tworker_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x13\n\x0boutput_json\x18\x05 \x01(\x0c\x12\x12\n\x05\x65rror\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07span_id\x18\x07 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x08 \x01(\x05\x42\x08\n\x06_errorB6Z4github.com/tomiwaaluko/helix/gen/go/helix/v1;helixv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helix.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/tomiwaaluko/helix/gen/go/helix/v1;helixv1'
  _globals['_TASKENVELOPE']._serialized_start=35
  _globals['_TASKENVELOPE']._serialized_end=272
  _globals['_TASKRESULT']._serialized_start=275
  _globals['_TASKRESULT']._serialized_end=452
# @@protoc_insertion_point(module_scope)
