/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs, optionally filtered by status. */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a run including its task tree. */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the span tree for a run. Returns 503 when ClickHouse is not configured. */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a run. Idempotent. */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RunStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        /** @enum {string} */
        TaskStatus: "pending" | "ready" | "running" | "succeeded" | "failed" | "cancelled" | "dead";
        Run: {
            id: string;
            workflow_id: string;
            status: components["schemas"]["RunStatus"];
            /** @description Raw JSON bytes (base64 in transit). */
            input?: string;
            output?: string;
            error?: string;
            /** Format: date-time */
            submitted_at: string;
            submitted_by: string;
            trace_id: string;
            task_ids?: string[];
        };
        Task: {
            id: string;
            run_id: string;
            node_id: string;
            status: components["schemas"]["TaskStatus"];
            attempts: number;
        };
        RunDetail: components["schemas"]["Run"] & {
            tasks: components["schemas"]["Task"][];
        };
        CancelResponse: {
            status?: string;
            run_id?: string;
        };
        SpanRecord: {
            span_id: string;
            parent_span_id?: string;
            run_id?: string;
            task_id?: string;
            attempt_number?: number;
            name: string;
            kind: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            duration_ms: number;
            status?: string;
            status_message?: string;
            service_name?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        TraceResponse: {
            trace_id: string;
            spans: components["schemas"]["SpanRecord"][];
        };
        ErrorResponse: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRuns: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs (most recent first, up to 100). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run with tasks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace with spans (blob attributes presigned to HTTPS URLs). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trace service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
        };
    };
}
