/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs, optionally filtered by status. */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a run including its task tree. */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the span tree for a run. Returns 503 when ClickHouse is not configured. */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a run. Idempotent. */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrievals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List retrieval rows (most recent first, up to 500). Returns 503 when ClickHouse is not configured. */
        get: operations["listRetrievals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List LLM call rows (most recent first, up to 500). Returns 503 when ClickHouse is not configured. */
        get: operations["listLlmCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List eval summaries (most recent first). Returns 503 when ClickHouse is not configured. */
        get: operations["listEvals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch per-example events for an eval run. */
        get: operations["getEval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finetune-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List finetune jobs (most recent first, up to 50). */
        get: operations["listFinetuneJobs"];
        put?: never;
        /** Start a mine → train → promote finetune job. */
        post: operations["createFinetuneJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finetune-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single finetune job by ID. */
        get: operations["getFinetuneJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embedding-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List embedding jobs (most recent first, up to 50). */
        get: operations["listEmbeddingJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embedding-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single embedding job by ID. */
        get: operations["getEmbeddingJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{eval_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record per-example eval scores from a Python harness run. */
        post: operations["recordEvalEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RunStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        /** @enum {string} */
        TaskStatus: "pending" | "ready" | "running" | "succeeded" | "failed" | "cancelled" | "dead";
        Run: {
            id: string;
            workflow_id: string;
            status: components["schemas"]["RunStatus"];
            /** @description Raw JSON bytes (base64 in transit). */
            input?: string;
            output?: string;
            error?: string;
            /** Format: date-time */
            submitted_at: string;
            submitted_by: string;
            trace_id: string;
            task_ids?: string[];
        };
        Task: {
            id: string;
            run_id: string;
            node_id: string;
            status: components["schemas"]["TaskStatus"];
            attempts: number;
        };
        RunDetail: components["schemas"]["Run"] & {
            tasks: components["schemas"]["Task"][];
        };
        CancelResponse: {
            status?: string;
            run_id?: string;
        };
        SpanRecord: {
            span_id: string;
            parent_span_id?: string;
            run_id?: string;
            task_id?: string;
            attempt_number?: number;
            name: string;
            kind: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            duration_ms: number;
            status?: string;
            status_message?: string;
            service_name?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        TraceResponse: {
            trace_id: string;
            spans: components["schemas"]["SpanRecord"][];
        };
        RetrievalRow: {
            trace_id: string;
            span_id: string;
            run_id: string;
            query: string;
            retriever: string;
            top_k: number;
            recall_at_k: number;
            /** Format: date-time */
            start_time: string;
            duration_ms: number;
        };
        LlmCallRow: {
            trace_id: string;
            span_id: string;
            run_id: string;
            provider: string;
            model: string;
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** Format: double */
            cost_usd: number;
            /** Format: date-time */
            start_time: string;
            duration_ms: number;
            status?: string;
        };
        ErrorResponse: {
            error?: string;
        };
        ScorerMean: {
            scorer: string;
            /** Format: double */
            mean: number;
            n: number;
        };
        EvalSummary: {
            eval_id: string;
            examples: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string;
            scorers: components["schemas"]["ScorerMean"][];
        };
        EvalEvent: {
            eval_id: string;
            example_id: string;
            run_id?: string;
            scorer: string;
            /** Format: double */
            score: number;
            passed: boolean;
            details?: string;
            /** Format: date-time */
            timestamp: string;
        };
        RecordEvalEventsRequest: {
            events: {
                example_id: string;
                run_id?: string;
                scorer: string;
                /** Format: double */
                score: number;
                passed: boolean;
                details?: {
                    [key: string]: unknown;
                };
            }[];
        };
        EmbeddingJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            finetune_job_id?: string | null;
            base_model: string;
            status: string;
            triplets_count?: number | null;
            metrics?: {
                [key: string]: unknown;
            } | null;
            artifact_uri?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            promoted_at?: string | null;
        };
        FinetuneJob: {
            id: string;
            run_id?: string;
            /** @description pending|mining|training|promoting|done|failed|promoted|archived|no_failures|no_triplets */
            status: string;
            train_split: string;
            eval_split: string;
            corpus_alias: string;
            failures?: number;
            triplets?: number;
            /** Format: double */
            before_recall?: number;
            /** Format: double */
            after_recall?: number;
            /** @description promoted|archived|no_failures|no_triplets|null */
            outcome?: string;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateFinetuneJobRequest: {
            /** @description Path or alias of the training dataset. */
            train_split: string;
            /** @description Path or alias of the evaluation dataset. */
            eval_split: string;
            /** @description Qdrant collection alias to mine and promote (default corpus.active). */
            corpus_alias?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRuns: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs (most recent first, up to 100). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run with tasks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace with spans (blob attributes presigned to HTTPS URLs). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trace service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
        };
    };
    listRetrievals: {
        parameters: {
            query?: {
                /** @description Filter by eval run ID. Returns all runs when omitted. */
                run_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieval rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalRow"][];
                };
            };
            /** @description Retrieval service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLlmCalls: {
        parameters: {
            query?: {
                /** @description Filter by eval run ID. Returns all runs when omitted. */
                run_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LLM call rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmCallRow"][];
                };
            };
            /** @description LLM call service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEvals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eval summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSummary"][];
                };
            };
            /** @description Eval service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-example eval events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalEvent"][];
                };
            };
            /** @description Eval not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Eval service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listFinetuneJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finetune jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinetuneJob"][];
                };
            };
            /** @description Finetune service not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createFinetuneJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFinetuneJobRequest"];
            };
        };
        responses: {
            /** @description Job created and dispatched. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinetuneJob"];
                };
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Finetune service not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFinetuneJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finetune job detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinetuneJob"];
                };
            };
            /** @description Job not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Finetune service not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEmbeddingJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Embedding jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingJob"][];
                };
            };
            /** @description Embedding service not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEmbeddingJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Embedding job detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingJob"];
                };
            };
            /** @description Job not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Embedding service not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recordEvalEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordEvalEventsRequest"];
            };
        };
        responses: {
            /** @description Events recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Eval service not configured (CLICKHOUSE_URL not set). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
